petstore/apps/adverts/urls.py
from django.conf.urls import patterns, url
from .views import AdvertWizard

urlpatterns = patterns('',
    url(r'^$', 'apps.adverts.views.all_adverts', name='all_adverts'),
    #url(r'^(\d+)/$', 'apps.adverts.views.view_advert', name='view_advert'),
    url(r'^(?P<advert_slug>[-\w\d]+),(?P<advert_id>\d+)/$', 'apps.adverts.views.view_advert', name='view_advert'),

    #url(r'^new$', 'apps.adverts.views.add_new_advert', name='new_advert'),
    url(r'^new$', AdvertWizard.as_view(), name='new_advert'),

    url(r'^update/(?P<advert_id>\d+)/$', 'apps.adverts.views.update_advert', name='update_advert'),
    url(r'^contact_seller/(?P<advert_id>\d+)/$', 'apps.adverts.views.contact_seller', name='contact_seller'),
    url(r'^search/$', 'apps.adverts.views.search_ads', name='search_ads'),
    url(r'^expired$', 'apps.adverts.views.view_expired_ads', name='expired_ads'),
    url(r'^user_ads/(?P<username>[-\w\d]+)/$', 'apps.adverts.views.all_user_adverts', name='user_ads'),
    url(r'^category/(?P<category_slug>[-\w\d]+),(?P<cat_id>\d+)/$', 'apps.adverts.views.all_category_ads', name='category_ads'),

    # Hitcount url to save hits on tutorial entity
    url(r'^ajax/hit/$', 'apps.adverts.views.update_hit_count_ajax', name='hitcount_update_ajax'),

    # AJAX Links
    url(r'^getsubcategories/', 'apps.adverts.views.getsubcategories'),
)

petstore/petstore/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from accountusers.forms import AuthLoginForm
from accountusers.views import LoginView, LogoutView, RegisterView, EmailSentView, ActivationView, LostPasswordView, LostPasswordEmailSentView, LostPasswordChangeView , UpdateUserView

urlpatterns = patterns('',
    url(r'^$', 'apps.adverts.views.home_page', name='home'),
    url(r'^ads/', include('apps.adverts.urls')),
    
    url(r'^contact/', 'apps.adverts.views.contact_us', name='contact_us'),
    url(r'^dashboard/', 'apps.adverts.views.view_dashboard', name='dashboard'),
    
    # user authentication and registration
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^profile/update/', UpdateUserView.as_view(), name='update_profile'),
    url(r'^registration_email_sent\.html', EmailSentView.as_view(), name='confirmation_mail_sent'),
    url(r'^user_activation\.html', ActivationView.as_view(), name='activation'),
    
    # user password handling
    url(r'^lost_password', LostPasswordView.as_view(), name='lost_password'),
    url(r'^lost_password_mail_sent', LostPasswordEmailSentView.as_view(), name='lost_password_mail_sent'),
    url(r'^reset_password', LostPasswordChangeView.as_view(), name='reset_password'),    
    url(r'^password_change/$', 
        'django.contrib.auth.views.password_change', 
        {'template_name': 'users/password_change_form.html'},
        name="password_change"),
    url(r'^password_change_done/$', 
        'django.contrib.auth.views.password_change_done', 
        {'template_name': 'users/password_change_done.html'},
        name="password_change_done"),
    
    # Static html files and other dynamic pages
    url(r'^about/', 'apps.adverts.views.about', name='about'),
    url(r'^terms/', 'apps.adverts.views.terms', name='terms'),
    url(r'^services/', 'apps.adverts.views.services', name='services'),
    url(r'^products/', 'apps.adverts.views.products', name='products'),
    
    # static files (images, css, javascript, etc.)
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    
    # robots.txt file
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    url(r'^admin/', include(admin.site.urls)),
)

# Overriding Django admin login form
admin.site.login_form = AuthLoginForm
admin.autodiscover()

petstore/apps/adverts/models.py
import os
import pytz
import uuid
from datetime import datetime, timedelta

from django.db import models
from django.db.models import Count
from django.core.urlresolvers import reverse
from django.core.validators import MinValueValidator
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

from .fixtures import COUNTY_LOCATIONS

utc = pytz.utc


class AdCategoryManager(models.Manager):

    def get_all_children(self, parentCat, include_self=True):
        subcat_list = []
        if include_self:
            subcat_list.append(parentCat)
        for category in self.filter(parent=parentCat):
            # using extend instead of append to create only one list, 
            # and not a list of lists
            subcat_list.extend(self.get_all_children(category, include_self=True))
        return subcat_list


class AdCategory(models.Model):
    title = models.CharField(_("Title"), max_length=100)
    slug = models.SlugField(max_length=100, db_index=True)
    parent = models.ForeignKey('self', blank=True, null=True)
    is_active = models.BooleanField(default=True)
    
    objects = AdCategoryManager()
    
    class Meta:
        unique_together = ('slug', 'parent',)
        ordering = ['-title']

    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('view_category', args=[self.id])
        
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)

        super(AdCategory, self).save(*args, **kwargs)


class AdvertManager(models.Manager):

    def all_approved_ads(self, **kwargs):
        return self.filter(status=1, **kwargs)
        
    def all_expired_ads(self, **kwargs):
        """
        Returns expired adverts
        """
        qs = super(AdvertManager, self).get_queryset()
        for advert in qs:
            if not advert.isexpired():
                # TODO: This is not very efficient. Results in a new queryset each time.
                qs = qs.exclude(pk=advert.pk)
        return qs.filter(**kwargs)
        
    def all_active_and_approved_ads(self):
        """
        Returns adverts that are NOT expired, and are approved
        """
        qs = self.all_approved_ads()
        for row in qs:
            if row.isexpired():
                # TODO: This is not very efficient. Results in a new queryset each time.
                qs = qs.exclude(pk=row.pk)
        return qs
        
    def get_user_ads(self, owner):
        return self.all_active_and_approved_ads().filter(owner=owner)
        
    def get_popular_ads(self, category):
        """
        Fetches popular ads for the given category (and all its subdirectories) 
        by counting the number of hitcounts on the advert.
        """
        sub_categories = AdCategory.objects.get_all_children(category)
        qs = self.all_active_and_approved_ads().filter(category__in=sub_categories)
        qs_popular = qs.annotate(num_view_count=Count('adverthitcounts')).order_by('-num_view_count')[:15]
        return qs_popular
        
    def get_premium_ads(self, category=None):
        """
        Fetches premium ads for the given category (and all its subdirectories) 
        if given.
        """
        if category:
            sub_categories = AdCategory.objects.get_all_children(category)
            qs = self.all_active_and_approved_ads().filter(is_featured=True, category__in=sub_categories)
        else:
            qs = self.all_active_and_approved_ads().filter(is_featured=True)
        return qs
        


class Advert(models.Model):

    # Ad Types
    PRICE = 1
    WANTED = 2
    TRADE = 3
    FREE = 4
    CONTACT = 5
    
    ADTYPES = (
        (PRICE, 'Priced Ad'),
        (WANTED, 'Item Wanted'),
        (TRADE, 'Will Barter/Trade'),
        (FREE, 'Free'),
        (CONTACT, 'Please Contact')
    )
    
    # Advert states
    PENDING = 0
    APPROVED = 1
    CANCELLED = 2

    ADVERT_STATES = (
        (PENDING, 'Pending approval'),
        (APPROVED, 'Approved'),
        (CANCELLED, 'Cancelled'),
    )

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, db_index=True, blank=False, null=False)
    title = models.CharField(_("Title"), max_length=120)
    slug = models.SlugField(max_length=100, db_index=True)
    description = models.TextField(_("Description"), default='')
    category = models.ForeignKey(AdCategory, db_index=True, related_name='ad_category', verbose_name=_('Category'))
    date_posted = models.DateTimeField(_('Date Posted'), db_index=True, default=datetime.now, auto_now_add=True)
    date_last_modified = models.DateTimeField(_('Date Last Modified'), 
                            db_index=True, null=True, blank=True, 
                            default=datetime.now, auto_now=True)
    status = models.IntegerField(choices=ADVERT_STATES, default=0)
    adtype = models.IntegerField(choices=ADTYPES, default=1)
    price = models.DecimalField(_('Price'), max_digits=12, decimal_places=2, blank=True, default=0,
                            help_text=_('Price'), validators=[MinValueValidator(0)])
    location = models.IntegerField(choices=COUNTY_LOCATIONS, default=30) # Defaults to Nairobi County
    expire_date = models.DateTimeField(_('Expiry Date'), null=True, blank=True)
    is_featured = models.BooleanField(default=False) # Same as premium i.e. is_premium
    
    objects = AdvertManager()
    
    class Meta:
        ordering = ('-date_posted',)
        verbose_name = _("Advert")
        verbose_name_plural = _("Adverts")
        
    def __str__(self):
        return self.title
        
    def get_absolute_url(self):
        return reverse('view_advert', args=[self.slug, self.id])
        
    def save(self, *args, **kwargs):
        if not self.id:
            # Newly created object, so set slug
            self.slug = slugify(self.title)
            
            # Set the initial advert status to pending approval
            self.status = 0
        
            # Set the expiration date 
            advert_activation_days = getattr(settings, 'ADVERT_VALID_DAYS', 30)

            if advert_activation_days:
                self.expire_date = datetime.now() + timedelta(days=advert_activation_days)

        super(Advert, self).save(*args, **kwargs)
        
    def isexpired(self):
        is_expired = False
        if utc.localize(datetime.now()) > self.expire_date:
            is_expired = True 
        return is_expired
        
        
def get_extension(filename):
    return os.path.splitext(filename)[1]
    

class AdvertImage(models.Model):

    def generate_new_filename(instance, filename):
        """
        Generate a new name for the given file
        """
        IMAGE_UPLOAD_DIR = "advert_images"
        old_fname, extension = os.path.splitext(filename)
        return '%s/%s%s' % (IMAGE_UPLOAD_DIR, uuid.uuid4().hex, extension)
    
    
    advert = models.ForeignKey(Advert, related_name='images')
    title = models.CharField(max_length=200, null=True, blank=True)
    image = models.ImageField(upload_to=generate_new_filename, null=True, blank=True)
    
    def __str__(self):
        return self.image.name or 'noname'
        
    def delete(self, *args, **kwargs):
        self.image.delete(False)
        super(AdvertImage, self).delete(*args, **kwargs)
        
        
class AdvertHitCountManager(models.Manager):

    def hits_in_last(self, **kwargs):
        """
        Returns hit count for an Advert during a given time period.

        This will only work for as long as hits are saved in the database.
        If you are purging your database after 45 days, for example, that means
        that asking for hits in the last 60 days will return an incorrect
        number, since the longest period it can search will be 45 days.
        
        For example: hits_in_last(days=7).

        Accepts days, seconds, microseconds, milliseconds, minutes, 
        hours, and weeks.  It's creating a datetime.timedelta object.
        """
        period = datetime.utcnow() - datetime.timedelta(**kwargs)
        return self.filter(created__gte=period).count()


class AdvertHitCount(models.Model):
    """
    Model captures a single Hit by a visitor.
    
    Depending on how long you want to be able to use 'Hit.hits_in_last(days=30)' 
    you should probably also occasionally clean out this database using a cron job.

    It could get rather large.
    """
    advert = models.ForeignKey(Advert, related_name='adverthitcounts')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=50)
    created = models.DateTimeField(default=datetime.now, auto_now_add=True)
    
    objects = AdvertHitCountManager()
    
    class Meta:
        ordering = ( '-created', )    
        get_latest_by = 'created'
        
    def __str__(self):
        return u'Hit: %s' % self.pk 
    

petstore/apps/adverts/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from django.forms import ModelForm, RadioSelect, TextInput

from .models import Advert, AdvertImage

class AdvertForm(ModelForm):

    class Meta:
        model = Advert
        fields = ('title', 'description', 'category', 'price', 'adtype', 'location')
        widgets = {
            'adtype': RadioSelect(),
            'price': TextInput(),
        }


class AdvertCategoryForm(ModelForm):
    """
    Form used in FormWizard for selecting categories
    """

    class Meta:
        model = Advert
        fields = ('category',)


class AdvertDetailsForm(ModelForm):
    """
    Form used in FormWizard for adding advert details.
    """

    class Meta:
        model = Advert
        fields = ('title', 'description', 'location', 'adtype', 'price')
        widgets = {
            'adtype': RadioSelect(),
            'price': TextInput(),
        }


class AdvertImageForm(ModelForm):

    class Meta:
        model = AdvertImage
        fields = ('image',)

AdvertImageFormset = inlineformset_factory(Advert, AdvertImage, fields=('image',), can_delete=False, extra=3, max_num=3)


class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder':'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Message'}))

# NOTE: If you change the name of the form, be sure to also change the JS variable in the template.
FORMS = [("ad_category", AdvertCategoryForm),
         ("ad_details", AdvertDetailsForm),
         ("ad_images", AdvertImageFormset)]

TEMPLATES = {"ad_category": "adverts/advert_category_step.html",
             "ad_details": "adverts/advert_details_step.html",
             "ad_images": "adverts/advert_images_step.html"}

petstore/templates/adverts/advert_listing.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- Head Title -->
{% block head_title %}{% if query %}{{ query }}{% else %}All Ad{% endif %} listings{% endblock %}

<!-- Meta Description -->
{% block meta_description %}
{% if query %}
    Find {{ query }} listings in Kenya at {{ SITE_NAME }}, the most popular free pet advertising website in Kenya. 
{% endif %}
{{ SITE_NAME }} is a free Kenyan Pet Advertising site for Dogs, Puppies, Cats and Kittens, Rabbits and all other pets in Kenya.
{% endblock %}

<!-- Meta Keywords -->
{% block meta_keywords %}
{% if query %}{{ query }}{% endif %}, buy sell pets in Kenya, dogs for sale, cats for sale, pets
{% endblock %}

{% block body %}

<!--Start Content Wrapper-->
	<div class="content_wrapper">
		<div class="container_24">
			<div class="grid_24">
				<div class="clear"></div>
				<div class="grid_17 alpha">
				
				    {% if adverts %}                            
                    <div class="">
                        <p>You searched for: <strong>{{ query }}</strong></p>
                        <p>Found <strong>{{ adverts|length }}</strong> advert{{ adverts|pluralize }}.</p>
                    </div>
				
					<!--Start Content-->
					<div class="content">
						
						<!--Start featured_item-->
					    <div class="featured_item">
						    <div id="wrap">
                                <header>
								    <span class="list-style-buttons">
									    <a href="#" id="gridview" class="switcher ">GRID VIEW</a>
									    <a href="#" id="listview" class="switcher active">LIST VIEW</a>
								    </span>
								    <ul id="tabs">
									    <li><a href="#" title="recent">RECENTLY LISTED</a></li>
									</ul>
								    <div class="clear"></div>
							    </header>
							    <div class="clear"></div>
							    <div id="content">
								    <div id="recent">
									    <ul id="products" class="list clearfix">
									    {% for advert in adverts %}
                                            <!-- row 1 -->
                                            <li class="thumbnail">
                                                <section class="thumbs">
                                                <!-- Show the first image -->
                                                {% with advert.images.all|first as image %}
                                                  {% if image %}
                                                  <a href="{% url 'view_advert' advert.slug advert.id %}">
                                                    <img src="{{ MEDIA_URL }}{{ image.image }}" class='postimg ' alt='Post Image'/>
                                                  </a>
                                                  {% else %}
                                                  <a href="{% url 'view_advert' advert.slug advert.id %}">
                                                    <img src="{% static 'images/NIA-thumb.jpg' %}" class='postimg ' alt='Post Image'/>
                                                  </a>
                                                  {% endif %} 
                                                {% endwith %}  
                                                    <section class="thumb_item">
                                                        <span class="price">
                                                        {% if advert.adtype == 1 %}
                                                            KES {{ advert.price }}
                                                        {% else %}
                                                            {{ advert.get_adtype_display }}
                                                        {% endif %}
                                                        </span>
                                                        <div class="clear"></div>
													    <a class="view" href="{% url 'view_advert' advert.slug advert.id %}">View it!</a>
												    </section>
											    </section>
											    <section class="contents">
												    <h6 class="title"><a href="{% url 'view_advert' advert.slug advert.id %}" rel="bookmark" title="links">{{ advert.title }}</a></h6>
											        <section class="grid_content">
											            <p>{{ advert.description|truncatewords:20 }} [&hellip;]</p>
											        </section>
										            <div class="clear"></div>
										            <ul class="post_meta">
											            <li class="estimate">{{ advert.date_posted|timesince }} ago</li>
											            <li class="cate"><a href="{% url 'category_ads' advert.category.slug advert.category.id %}" rel="tag">{{ advert.category }}</a></li>
											            <li class="author">by&nbsp;<a href="{% url 'user_ads' advert.owner.username %}" title="Posts by {{ advert.owner }}" rel="author">{{ advert.owner }}</a></li>
										            </ul>
										        </section>
										    </li>
                                            <!-- row 1 --> 
                                            {% endfor %}  
								        </ul>
								        
								        <!-- Adverts Pagination -->
								        <ul class="paginate">
								            {% if adverts.has_previous %}
                                                <li><a href="?page=1">&#171;</a></li>
                                                <li><a href="?page={{ adverts.previous_page_number }}">&#8249;</a></li>
                                            {% endif %}
								            
								            <li><a href="?page={{ adverts.number }}" class="current">Page {{ adverts.number }} of {{ adverts.paginator.num_pages }}</a></li>
								            
								            {% if adverts.has_next %}
                                                <li><a href="?page={{ adverts.next_page_number }}">&#8250;</a></li>
                                                <li><a href="?page={{ adverts.num_pages }}">&#187;</a></li>
                                            {% endif %}      
								        </ul>
								        <!-- End of Adverts Pagination -->
								           
								    </div>                                     
							    </div>
						        <div class="clear"></div>
					        </div>
                        
                        </div>
				        <!--End featured_item-->  
					</div>
					<!--End Content-->
					
					{% else %}
                    <div class="">
                        <p>You searched for: <strong>{{ query }}</strong></p>
                        <p>No adverts matched your search criteria.</p>
                    </div>
                    {% endif %}					
					
				</div>
				<div class="grid_7 omega">
					{% include 'sidebar.html' %}
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<!--End Content Wrapper-->

{% endblock %}

petstore/templates/adverts/dashboard.html
{% extends "base.html" %}
{% load staticfiles %}

{% block head_title %}Dashboard{% endblock %}

{% block body %}

<!--Start Content Wrapper-->
<div class="content_wrapper">
    <div class="container_24">
        <div class="grid_24">
            <div class="grid_17 alpha">
                <!--Start Content-->
                <div class="content" id="dashboard">
                    
                    <div class="box-head"><h2>Your Ads</h2></div>
                    <div class="box-content no-pad">
                        <table class="display dataTable">
                            <thead>                                   
                                <tr>
                                    <th>Ad Title</th>
                                    <th>Views</th>
                                    <th>Status</th>
                                    <th>Options</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% if adverts %}
                                {% for advert in adverts %}
                                <tr class="{% if forloop.counter|divisibleby:2 %}even{% else %}odd{% endif %}">
                                    <td>{{ advert.title }}</td>
                                    <td>{{ advert.adverthitcounts.count }} Views</td>
                                    <td>{{ advert.get_status_display }}</td>
                                    <td>
                                        <a href="{% url 'update_advert' advert.id %}" title="Edit Ad"><img src="{% static 'images/pencil.png' %}"/></a>&nbsp; 
                                        <a href="#" title="Delete Ad"><img src="{% static 'images/cross.png' %}"/></a>
                        
                                    </td>
                                </tr>
                                {% endfor %}
                            {% else %}
                                <tr>
                                    <td colspan="4">
                                        <p>You currently have no ads.</p>   
                                    </td>
                                </tr>
                            {% endif %}                                           
                            </tbody>
                        </table>
                        <p></p>
                    </div>
                    <div class="clear"></div>
                </div>
                <!--End Content-->
            </div>
            <div class="grid_7 omega">
                {% include 'sidebar_dashboard.html' %}    
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<!--End Content Wrapper-->                    

{% endblock %}

petstore/templates/adverts/view_advert.html
{% extends "base.html" %}
{% load staticfiles %}

<!-- Head Title -->
{% block head_title %}{{ advert.title }}{% endblock %}

<!-- Meta Description -->
{% block meta_description %}{{ advert.description|truncatewords:30 }}{% endblock %}

<!-- Meta Keywords -->
{% block meta_keywords %}{{ advert.category }} for sale, pets in {{ advert.get_location_display }}, buy sell pets in kenya{% endblock %}

{% block body %}

<!--Start Content Wrapper-->
<div class="content_wrapper">
    <div class="container_24">
        <div class="grid_24">
            <div class="grid_17 alpha">
            
            <script type="text/javascript">
            jQuery(document).ready(function(){
                var csrf_token = '{{ csrf_token }}';
                {{ hitcount_js|safe }}
            });
            </script>
            
            
                <!--Start Content-->
                <div class="content">
                    <!--Start Post-->
                    <div class="post classi">
                        <div class="post_content">
                            <h1 class="post_title">{{ advert.title }}</h1>
                                <span class="price_meta">
                                    <span class="price_left"></span>
                                    <span class="price_center">
                                        {% if advert.adtype == 1 %}
                                            {{ advert.price }}
                                        {% else %}
                                            {{ advert.get_adtype_display }}
                                        {% endif %}
                                    </span>
                                    <span class="price_right"></span>
                                </span>
                                <ul class="post_meta">
                                    <li class="estimate">{{ advert.date_posted|timesince }} ago</li>
                                    <li class="cate">In&nbsp;<a href="{% url 'category_ads' advert.category.slug advert.category.id %}" rel="tag">{{ advert.category }}</a></li>
                                    <li class="author">by&nbsp;<a href="{% url 'user_ads' advert.owner.username %}" title="Posts by {{ advert.owner }}" rel="author">{{ advert.owner }}</a></li>
                                </ul>  

                                <div class="meta_boxes">
                                    <div class="meta_slider">
                                        <div class="flexslider">
                                            <ul class="slides">
                                            {% if advert.images.count|add:0 == 0 %}
                                                <li><img src="{% static 'images/NIA.jpg' %}" /> </li>
                                            {% else %}
                                                {% for image in advert.images.all %}
                                                    <li><img src="{{ MEDIA_URL }}{{ image.image }}" /> </li>
                                                {% endfor %} 
                                            {% endif %}   
                                            </ul>
                                        </div>
                                    </div>
                                    <div class="meta_table">
                                        <table class="ar_desc">
                                            <tr>
                                                <td class="label">Location</td>
                                                <td>{{ advert.get_location_display }}</td>
                                            </tr>
                                            <tr>
                                                <td class="label">Country</td>
                                                <td>Kenya</td>
                                            </tr>
                                            <tr>
                                                <td class="label">Expires</td>
                                                <td>{{ advert.expire_date|timeuntil }}</td>
                                            </tr>                                        
                                        </table>
                                    </div>
                                    <div class="clear"></div>
                                </div>
                                <div class="clear"></div>
                                <span class="views">{{ advert.adverthitcounts.count }} Views</span>
                            </div>
                        </div>
                        <!--End Post-->
                        <div class="clear"></div>
                        <nav id="nav-single"> 
                            <span class="nav-previous">
                                <a href="#" rel="prev"><span class="meta-nav">&larr;</span> Previous Ad </a>
                            </span> 
                            <span class="nav-next">
                                <a href="#" rel="next">Next Ad <span class="meta-nav">&rarr;</span></a>
                            </span> 
                        </nav>
                        <div class="post_content">
                            <p>{{ advert.description }}</p>
                        </div>
                        
                        <div class="clear"></div>                   
                </div>
                <!--End Content-->
            </div>
            <div class="grid_7 omega">
                {% include 'sidebar_contact.html' %}    
            </div>
        </div>
        <div class="clear"></div>
    </div>
</div>
<!--End Content Wrapper-->                    

{% endblock %}