petstore/petstore/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

from accountusers.forms import AuthLoginForm
from accountusers.views import LoginView, LogoutView, RegisterView, EmailSentView, ActivationView, LostPasswordView, LostPasswordEmailSentView, LostPasswordChangeView , UpdateUserView

urlpatterns = patterns('',
    url(r'^$', 'apps.adverts.views.home_page', name='home'),
    url(r'^ads/', include('apps.adverts.urls')),
    
    url(r'^contact/', 'apps.adverts.views.contact_us', name='contact_us'),
    url(r'^dashboard/', 'apps.adverts.views.view_dashboard', name='dashboard'),
    
    # user authentication and registration
    url(r'^login/', LoginView.as_view(), name='login'),
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    url(r'^register/', RegisterView.as_view(), name='register'),
    url(r'^profile/update/', UpdateUserView.as_view(), name='update_profile'),
    url(r'^registration_email_sent\.html', EmailSentView.as_view(), name='confirmation_mail_sent'),
    url(r'^user_activation\.html', ActivationView.as_view(), name='activation'),
    
    # user password handling
    url(r'^lost_password', LostPasswordView.as_view(), name='lost_password'),
    url(r'^lost_password_mail_sent', LostPasswordEmailSentView.as_view(), name='lost_password_mail_sent'),
    url(r'^reset_password', LostPasswordChangeView.as_view(), name='reset_password'),    
    url(r'^password_change/$', 
        'django.contrib.auth.views.password_change', 
        {'template_name': 'users/password_change_form.html'},
        name="password_change"),
    url(r'^password_change_done/$', 
        'django.contrib.auth.views.password_change_done', 
        {'template_name': 'users/password_change_done.html'},
        name="password_change_done"),
    
    # Static html files and other dynamic pages
    url(r'^about/', 'apps.adverts.views.about', name='about'),
    url(r'^terms/', 'apps.adverts.views.terms', name='terms'),
    url(r'^services/', 'apps.adverts.views.services', name='services'),
    url(r'^products/', 'apps.adverts.views.products', name='products'),
    
    # static files (images, css, javascript, etc.)
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    
    # robots.txt file
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),

    url(r'^admin/', include(admin.site.urls)),
)

# Overriding Django admin login form
admin.site.login_form = AuthLoginForm
admin.autodiscover()

petstore/accountusers/forms.py
from __future__ import absolute_import
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField, UserCreationForm, UserChangeForm, AuthenticationForm
from django.db.models import Q
from django.contrib.auth import get_user_model
from django.forms import TextInput

from .models import AuthUser, Registration


class AuthUserCreationForm(UserCreationForm):
    """
    A form for creating new users, with no privileges, from the given email and
    password. Includes all the required fields, plus a repeated password.
    """
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    
    class Meta:
        model = AuthUser
        fields = ('username', 'email',)
        
    def clean_username(self):
        username = self.cleaned_data["username"]
        
        try:
            AuthUser._default_manager.get(username=username)
        except AuthUser.DoesNotExist:
            return username
        raise forms.ValidationError(self.error_messages['duplicate_username'])
    
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2
        
    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(AuthUserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
        
        
class AuthUserChangeForm(UserChangeForm):
    """
    A form for updating users. Includes all the fields on the user, but 
    replaces the password field with admin's password hash display field.
    """
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly':'readonly'}))
    password = ReadOnlyPasswordHashField(label="password",
                                         help_text="""Raw passwords are not stored, so there is no way to see this
                                         user's password, but you can change the password using <a href=\"password/\">
                                         this form</a>""")

    class Meta:
        model = AuthUser
        fields = ('username', 'email', 'password', 'is_active', 'is_staff', 'is_superuser', 'user_permissions')
        widgets = {
            'email': TextInput(),
        }

    def clean_username(self):
        # Regardless of what the user provides, reset field to initial value
        # Not appropriate to change usernames once set.
        return self.initial["username"]
        
    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the field does 
        # not have access to the initial value
        return self.initial["password"]
        
    def clean_is_active(self):
        return self.initial["is_active"]
        
        
class LoginFormMixin(object):
   
    # This is where our logic will take place

    username = forms.CharField(label = 'Username or e-mail', required=True)
    password  = forms.CharField(label = 'Password', widget = forms.PasswordInput, required = True)
 
    def clean(self):
        username = self.cleaned_data.get('username', '')
        password = self.cleaned_data.get('password', '')
        self.user = None
        users = AuthUser.objects.filter(Q(username=username)|Q(email=username))
        for user in users:
            if user.is_active and user.check_password(password):
                self.user = user
        if self.user is None:
            raise forms.ValidationError('Invalid username or password')
        # We are setting the backend here so you may (and should) remove the line setting it in apps.accountauth.views
        self.user.backend = 'django.contrib.auth.backends.ModelBackend'
        return self.cleaned_data
        
        
class LoginForm(forms.Form):                           
         
    login = forms.CharField(label = 'Username or e-mail', required=True)                                         
    password  = forms.CharField(label = 'Password', widget = forms.PasswordInput, required = True)
       
    def clean(self):                                     
        login = self.cleaned_data.get('login', '')         
        password = self.cleaned_data.get('password', '')
        self.user = None
        users = get_user_model().objects.filter(Q(username=login)|Q(email=login))
        for user in users:
            if user.is_active and user.check_password(password):
                self.user = user
        if self.user is None:
            raise forms.ValidationError('Invalid username or password')
        return self.cleaned_data
        
        
class AuthLoginForm(LoginFormMixin, AuthenticationForm):
 
    # Because of the way Python's MRO works we have to redefine username which has been overridden by AuthenticationForm
    username = forms.CharField(label = 'Username or e-mail', required=True)
    this_is_the_login_form = forms.BooleanField(widget=forms.HiddenInput, initial=1, error_messages={'required': "Please log in again, because your session has expired."})
 
    def clean(self):
        cleaned_data = super(AuthLoginForm, self).clean()
        if self.user is not None:
            self.user_cache = self.user
        return cleaned_data
        
        
class UserRegistrationForm(AuthUserCreationForm):
 
    class Meta:
        # Since we are overriding Meta we have to re-tell it the model also
        model = AuthUser
        exclude = ['password', 'last_login', 'date_joined', 'groups', 'user_permissions', 'is_staff', 'is_superuser', 'is_active']
        
        
class LostPasswordForm(forms.Form):
 
    email = forms.EmailField(label='E-mail address')
     
    def clean(self):
        cleaned_data = super(LostPasswordForm, self).clean()
        try:
            user = AuthUser.objects.get(email=cleaned_data['email'], is_active=True)
        except User.DoesNotExist:
            raise forms.ValidationError("We don't know of any user with that e-mail address")
        return cleaned_data
        

class LostPasswordChangeForm(forms.ModelForm):
 
    id = forms.IntegerField(widget=forms.HiddenInput())
    password1 = forms.CharField(label="Password", min_length=8, widget=forms.PasswordInput())
    password2 = forms.CharField(label="Password confirmation", widget=forms.PasswordInput())
 
    class Meta:
        model = Registration
        fields = ['id',]    
 
    def clean_password2(self):
        cleaned_data = super(LostPasswordChangeForm, self).clean()
        self.password = cleaned_data.get('password1')
        if self.password != cleaned_data.get('password2'):
            raise forms.ValidationError('Password do not match')
        self.user = self.instance.user
        return self.password
        

petstore/apps/adverts/forms.py
from django.forms.models import inlineformset_factory
from django import forms
from django.forms import ModelForm, RadioSelect, TextInput

from .models import Advert, AdvertImage

class AdvertForm(ModelForm):

    class Meta:
        model = Advert
        fields = ('title', 'description', 'category', 'price', 'adtype', 'location')
        widgets = {
            'adtype': RadioSelect(),
            'price': TextInput(),
        }


class AdvertCategoryForm(ModelForm):
    """
    Form used in FormWizard for selecting categories
    """

    class Meta:
        model = Advert
        fields = ('category',)


class AdvertDetailsForm(ModelForm):
    """
    Form used in FormWizard for adding advert details.
    """

    class Meta:
        model = Advert
        fields = ('title', 'description', 'location', 'adtype', 'price')
        widgets = {
            'adtype': RadioSelect(),
            'price': TextInput(),
        }


class AdvertImageForm(ModelForm):

    class Meta:
        model = AdvertImage
        fields = ('image',)

AdvertImageFormset = inlineformset_factory(Advert, AdvertImage, fields=('image',), can_delete=False, extra=3, max_num=3)


class ContactForm(forms.Form):
    name = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder':'Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder':'Email'}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Message'}))

# NOTE: If you change the name of the form, be sure to also change the JS variable in the template.
FORMS = [("ad_category", AdvertCategoryForm),
         ("ad_details", AdvertDetailsForm),
         ("ad_images", AdvertImageFormset)]

TEMPLATES = {"ad_category": "adverts/advert_category_step.html",
             "ad_details": "adverts/advert_details_step.html",
             "ad_images": "adverts/advert_images_step.html"}

petstore/templates/about.html
{% extends 'base.html' %}

{% block head_title %}About Us{% endblock %}

{% block body %}

<!--Start Content Wrapper-->
<div class="content_wrapper">
    <div class="container_24">
        <div class="grid_24">
            
            <!--Start Content-->
            <div class="content">
                <h1 class="page_title">About Us</h1>
                <p>Thank you for visiting the {{ SITE_NAME }} free online pet classifieds website. We are the Kenya&rsquo;s most popular classfieds website for various kinds of Pets including Cats, Dogs, Rabbits and Horses to name a few. We are also totally free to use.</p>
                
                <p>The {{ SITE_NAME }} website was started in September 2014 and has quickly grown to become the Kenya&rsquo;s leading free advertising site for pets.</p>
                
                <h3>What We DO</h3>
                <p>The {{ SITE_NAME }} website provides a totally free to use advertising platform for private individuals, responsible breeders and rescue centres to list their adverts on. Potential buyers or adopters of pets can use the website to make initial contact with the advertisers. We also provide information and advice for potential pet owners.</p>
                
                <h3>Do We Check The Adverts Placed on Our Site</h3>
                <p>Yes, we manually approve the majority of adverts that are placed on our {{ SITE_NAME }} website. However we do not visit any of the advertisers homes or do any checks on the advertisers, therefore, it is the buyers responsibility to make any necessary checks on the advertisers before buying or adopting a pet.</p>
                
                <h3>Do you prevent puppy farmers or dodgy breeders abusing your site?</h3>
                <p>Yes, we do our best to prevent puppy farmers from trying to use our website. We do this by monitoring the number of adverts we allow each advertiser to place, and check advertisers local authority breeders licenses to make sure they are valid. We also work very closely with animal welfare organisations to prevent known puppy farmers from using our website.</p>
                
                <h3>What kind of adverts do you not allow on the site?</h3>
                <p>We have a list of standards we have created that we stick to when approving or banning adverts. You can read them by clicking <a href="{% url 'terms' %}#standards">here</a>. We also try to follow the WSPA and KSPCA minimum standards.</p>
                
                <h3>How can I can contact {{ SITE_NAME }}?</h3>
                <p>{{ SITE_NAME }} pet classifieds website is run by a very small team and is a totally free service, therefore we are currently unable to provide telephone support, but you can contact us via email using our &lsquo;<a href="{% url 'contact_us' %}">Contact Us</a>&rsquo; form, or alternatively write to us at our address below, and we will try to reply to you as soon as we can :</p>
                
                <p>
                PetsFirst,<br/>
                P.O. Box 384,<br/>
                Nairobi - Kenya.<br/>
                info@petsfirst.co.ke
                </p>
                
                <p>
                Regards,<br/>
                The {{ SITE_NAME }} Team</p>
                
                
                
            </div>
            <!--End Content-->
           
           
                
               
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<!--End Content Wrapper-->

{% endblock %}

petstore/templates/contact_us.html
{% extends 'base.html' %}

{% block head_title %}Home{% endblock %}

{% block body %}

<!--Start Content Wrapper-->
<div class="content_wrapper">
    <div class="container_24">
        <div class="grid_24">
            <div class="grid_17 alpha">
                <!--Start Content-->
                <div class="content">
                    <h1 class="page_title">Contact Us</h1>
                    <div id="contact">
                        {{ contact_form.non_field_errors }}
                        <form action="{% url 'contact_us' %}" class="contactform" method="post" id="contactForm">
                            {% csrf_token %}
                        
                            <label for="contactName">Your Name <span class="required">*</span></label>
                            <br/>                                                        
                            {{ contact_form.name }}
                            <span id="username_error"></span>
                            <br/>
                            
                            <label for="eMail">Your Email: <span class="required">*</span></label>
                            <br/>                                                        
                            {{ contact_form.email }}
                            <span id="email_error"></span>
                            <br/>
                            
                            <label for="commentsText">Your Message <span class="required">*</span></label>
                            <br/>
                            {{ contact_form.message }}
                            <span id="comment_error"></span>
                            <br/>
                            
                            <input class="captcha" id="captcha" placeholder="Enter Captcha" type="text" name="captcha" value=""/>
                            <span style="" class="show_captcha">3 + 1</span>
                            <div class="clear"></div>
                            <input type="hidden" name="captchacode" value="4"/>
                            
                            <input  class="btnSubmit" type="submit" name="submit" value="Submit"/>
                            <input type="hidden" name="submitted" id="submitted" value="true" />
                        </form>                         
                    </div>
                </div>
                <!--End Content-->
            </div>
           <script type="text/javascript">
            jQuery(document).ready(function(){
                var Form = jQuery("#contactForm");
                var uname = jQuery('#id_name');
                var email = jQuery("#id_email");
                var message = jQuery("#id_message");
                var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
                function validate_uname(){
                    if(uname.val() == ''){
                        uname.addClass('error');
                        uname.css('border', 'solid 1px red');
                        uname.attr("placeholder","This field is required");
                        return false;
                    }else{
                        uname.removeClass('error');
                        uname.css("border","none");
                        return true;
                    }
                }
                uname.blur(validate_uname);
                uname.keyup(validate_uname);
                
                function validate_email(){
                    if(email.val() == ''){
                        email.addClass('error');
                        email.css("border", "solid 1px red");
                        email.attr("placeholder","This field is required");
                        return false;
                    }else if(!emailReg.test(email.val())){
                        email.addClass("error");
                        email.css("border", "solid 1px red");
                        email.attr("placehoder", "Please provide valid email address");
                        return false;
                    }else{
                        email.removeClass("error");
                        email.css("border","none");
                        return true;
                    }
                }
                email.blur(validate_email);
                email.keyup(validate_email);
                            
                function validate_message(){
                    if(message.val() == ''){
                        message.addClass("error");
                        message.css("border","solid 1px red"); 
                        message.attr("placeholder","This field is required");
                        return false;
                    }else{
                        message.removeClass("error");
                        message.css("border","none");
                        return true;
                    }
                }
                message.blur(validate_message);
                message.keyup(validate_message);
                Form.submit(function(){
                    if(validate_uname() & validate_email() & validate_message()){
                        return true;
                    }else{
                        return false;
                    }
                });
            });   
        </script>
                
                <div class="grid_7 omega">
					{% include 'sidebar.html' %}
				</div>
			</div>
			<div class="clear"></div>
		</div>
	</div>
	<!--End Content Wrapper-->

{% endblock %}

petstore/templates/sidebar.html
{% load categories_list %}
{% load staticfiles %}

                <!--Start Sidebar-->
                <div class="sidebar">
                    <div class="sidebar_widget">
                        <h4 class="widget-title">Categories</h4>
                        {% if category %}
                            {% get_category_list category %}
                        {% else %}
                            {% get_category_list %}
                        {% endif %}
                    </div>
                    <div class="sidebar_widget">
                        <h4 class="head">Recent Ads</h4>
                        <img src="{% static 'images/AdvertiseHere.jpg' %}" alt="Advertise Here" width="250" />
                    </div>
                </div>
                <!--End Sidebar-->

petstore/templates/sidebar_contact.html
<!--Start Sidebar-->
<div class="sidebar">
    <!--Start sidebar_widget-->
<div class="sidebar_widget">
    <div class="contact_widget">
        <div class="subscribe_form">
            <h5 class="contact_header">Contact This Person</h5>
            <div class="form_element">
                {{ seller_contact_form.non_field_errors }}
                <form id="lead_form" action="{% url 'contact_seller' advert.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    
                    {{ seller_contact_form.name }}
                    {{ seller_contact_form.email }}
                    {{ seller_contact_form.message }}
                    <input class="captcha" id="captcha" placeholder="Enter Captcha" type="text" name="captcha" value=""/>
                    <span style="" class="show_captcha">3 + 1</span>
                    <div class="clear"></div>
                    <input type="hidden" name="captchacode" value="4"/>                  
                    <input type="submit" name="submit"/>                    
                </form>
                <script type="text/javascript">
                jQuery(document).ready(function(){
                    var Form = jQuery("#lead_form");
                    var uname = jQuery('#id_name');
                    var email = jQuery("#id_email");
                    var message = jQuery("#id_message");
                    var emailReg = /^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;
                    var captcha = jQuery('#captcha');
                    function validate_uname(){
                        if(uname.val() == ''){
                            uname.addClass('error');
                            uname.css('border', 'solid 1px red');
                            uname.attr("placeholder","This field is required");
                            return false;
                        }else{
                            uname.removeClass('error');
                            uname.css("border","1px solid #c3c3c3");
                            return true;
                        }
                    }
                    uname.blur(validate_uname);
                    uname.keyup(validate_uname);        
                    function validate_email(){
                        if(email.val() == ''){
                            email.addClass('error');
                            email.css("border", "solid 1px red");
                            email.attr("placeholder","This field is required");
                            return false;
                        }else if(!emailReg.test(email.val())){
                            email.addClass("error");
                            email.css("border", "solid 1px red");
                            email.attr("placehoder", "Please provide valid email address");
                            return false;
                        }else{
                            email.removeClass("error");
                            email.css("border","1px solid #c3c3c3");
                            return true;
                        }
                    }
                    email.blur(validate_email);
                    email.keyup(validate_email);
                                
                    function validate_message(){
                        if(message.val() == ''){
                            message.addClass("error");
                            message.attr("placeholder","This field is required");
                            message.css("border","solid 1px red"); 
                            return false;
                        }else{
                            message.removeClass("error");
                            message.css("border","1px solid #c3c3c3");
                            return true;
                        }
                    }
                    message.blur(validate_message);
                    message.keyup(validate_message);
                    function validate_captcha(){
                        if(captcha.val() == ''){
                            captcha.addClass("error");
                            captcha.attr("placeholder","This field is required");
                            captcha.css("border","solid 1px red"); 
                            return false;
                        }else{
                            captcha.removeClass("error");
                            captcha.css("border","1px solid #c3c3c3");
                            return true;
                        } 
                    }
                    captcha.blur(validate_captcha);
                    captcha.keyup(validate_captcha);
                    Form.submit(function(){
                        if(validate_uname() & validate_email() & validate_message() & validate_captcha()){
                            return true;
                        }else{
                            return false;
                        }
                    });
                });   
                </script>
            </div>
        </div>
    </div>
</div>
<!--End sidebar_widget-->
<div class="sidebar_widget">
    
</div>
<div class="clear"></div>
<div class="sidebar_widget">
<h4 class="widget-title">Categories</h4>
        <!--<ul>
                	<li class="cat-item cat-item-45"><a href="http://inkthemes.com/wptheme/classicraft/cate/accounts-finance-law-jobs/" title="View all posts filed under Accounts, Finance &amp; Law Jobs">Accounts, Finance &amp; Law Jobs</a>
</li>
	<li class="cat-item cat-item-46"><a href="http://inkthemes.com/wptheme/classicraft/cate/admin-support-jobs/" title="View all posts filed under Admin &amp; Support Jobs">Admin &amp; Support Jobs</a>
</li>
	<li class="cat-item cat-item-36"><a href="http://inkthemes.com/wptheme/classicraft/cate/agriculture-equipment/" title="View all posts filed under Agriculture Equipment">Agriculture Equipment</a>
</li>
	<li class="cat-item cat-item-52"><a href="http://inkthemes.com/wptheme/classicraft/cate/apartments-flats-for-sale/" title="View all posts filed under Apartments &amp; Flats for Sale">Apartments &amp; Flats for Sale</a>
</li>
	<li class="cat-item cat-item-60"><a href="http://inkthemes.com/wptheme/classicraft/cate/architects-interior-designers/" title="View all posts filed under Architects &amp; Interior Designers">Architects &amp; Interior Designers</a>
</li>
	<li class="cat-item cat-item-39"><a href="http://inkthemes.com/wptheme/classicraft/cate/art-entertainment/" title="View all posts filed under Art &amp; Entertainment">Art &amp; Entertainment</a>
</li>
	
            </ul>-->
            </div><div class="sidebar_widget">     
        <h5 class="head">Recent Ads</h5>
        
        </div></div>
<!--End Sidebar-->      

petstore/templates/sidebar_dashboard.html
{% load staticfiles %}
                <!--Start Sidebar-->
                <div class="sidebar">
                    <div class="sidebar_dashboard">
                        <h2 class="head">Account Information</h2>
                        <div class="author-meta">
                            <img alt='' src="{% static 'images/empty_profile.png' %}" class='avatar avatar-40 photo' height='40' width='40' />
                            <h4>Welcome,&nbsp;{{ user.username }}</h4>
                            <small>Member Since :&nbsp;{{ user.date_joined|date:'d/M/y' }}</small>
                        </div>
                    </div>
                    
                    <div class="sidebar_dashboard">
                        <h2 class="head">User Options</h2>                         
                        <ul class="dash-list">
                            <li class="addnew"><a href="{% url 'new_advert' %}">Add New</a></li>
                            <li class="view"><a href="{% url 'dashboard' %}">View Ads</a></li>
                            <!--<li class="comment"><a href="#">View comments</a></li>
                            <li class="lead"><a href="#">View Leads</a></li>-->
                            <li class="expire"><a href="{% url 'expired_ads' %}">View Expired Ads</a></li>
                            <li class="profile"><a href="{% url 'update_profile' %}">Edit Profile</a></li>
                            <li class="profile"><a href="{% url 'password_change' %}">Change Password</a></li>
                        </ul>
                    </div>
                </div>
                <!--End Sidebar-->

petstore/templates/slider.html
{% load slider_adverts %}

<div id="slider_wrapper">
    {% get_slider_adverts %}
</div>